# This workflow is based on the jupyter-book template:
# https://github.com/executablebooks/cookiecutter-jupyter-book/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/.github/workflows/deploy.yml

name: Build and Deploy Jupyter Book

# Run this workflow every time a new commit is pushed to the main branch
on:
  push:
    branches:
      - main

# Grant GITHUB_TOKEN permissions to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Deploy to GitHub Pages
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build the Jupyter Book
        run: |
          pip install -r requirements.txt
          # Use --all to force a clean build
          jupyter-book build . --all

      - name: List files in workspace (for debugging)
        run: |
          echo "--- Listing all files in the current directory ---"
          ls -laR
          echo "--- End of file listing ---"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
